services:
  database:
    image: mysql:8.0.40
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'Abner'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '1234567'
    ports:
       - '3306:3306'
    expose:
       - '3306'
    volumes:
       - mydb:/var/lib/mysql
       - ./src/main/resources/static/inicial.sql:/docker-entrypoint-initdb.d/inicial.sql
volumes:
  mydb:
